module.exports.technology = [
  "Portable Chargers",
  "Car Mounts",
  "Selfie Sticks",
  "Camera Lens Attachments",
  "Gimbals",
  "USB OTG Flash Drives",
  "Headphones",
  "Bluetooth Earbuds",
  "Smartwatches",
  "Gaming Controllers",
  "Skins",
  "Cases and Covers",
  "Screen Protectors",
  "Portable Bluetooth Speakers",
  "Car Chargers",
  "Charging Stations",
  "Headphone Adapter",
  "Phone Ring Holder",
  "Waterproof Pouch",
  "Multiport Wall Charger",
];

module.exports.company = [
  "AZ Technology Inc",
  "Behance LLC",
  "Advanced Players",
  "Blue Space",
  "Centric Services",
  "CO-AX Inc.",
  "Cyber Group",
  "Golden Section",
  "High Tech Fabrication",
  "Kingston Ttechnology Co Inc.",
  "Micron Technology Inc.",
  "Optionscity Software Inc.",
  "Nationwide Group",
  "Riverbed Technology",
  "S4 Technologies",
  "SilkRoad",
  "Seaco Technologies",
  "SWC Technology Partners",
  "Technology Informer",
  "Trade Technologies",
  "Warrior",
  "Woodlands Corp.",
  "Worldwide Tech Services",
  "Techcess Group",
  "Target Technology Co",
  "Sky High Tech",
  "Seppi Technology Associates",
  "Root Level",
  "Percento",
  "Lighthose",
];
